### ISSUE TITLE
blog fixes

### ISSUE THREAD

**Issue by ksurl** [JackCuthbert/JackCuthbert#1]
hi there, I came across your blog post about gpu passthrough on proxmox for plex in docker. I couldn't find any other way to contact you since your discord link is also dead, and you aren't accepting twitter dm's. 

I had to make sure the uid I was running plex as had permission to `/dev/dri` which is usually the `video` group (in my case, gid 226). rather than change permissions on the folder, I just added that user on the docker host/vm to `video`.

**Comment by JackCuthbert** [comment]
Oh thanks! Sorry about the contact issues, I haven't updated my site in quite some time :speak_no_evil: 

I'll add a note to the post tomorrow detailing this, thanks for the feedback! Much appreciated :pray:
